name: Build, Test & Publish Docker image

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-test-push:
    runs-on: self-hosted-arm
    timeout-minutes: 20

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Extract distro from Dockerfile
        id: get_distro
        shell: bash
        run: |
          DISTRO=$(grep -m1 '^FROM ' Dockerfile.dockerfile | cut -d':' -f2)
          echo "Found distro  $DISTRO"
          echo "DISTRO=$DISTRO" >> $GITHUB_ENV

      - name: Show distro / arch
        run: echo " Building for distro=${{ env.DISTRO }}, arch=${{ matrix.arch }}"

      - name: Set up QEMU (для cross-build)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.dockerfile
          push: true
          platforms: linux/${{ matrix.arch }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.DISTRO }}-${{ matrix.arch }}
            ghcr.io/${{ github.repository }}:${{ env.DISTRO }}
            ghcr.io/${{ github.repository }}:latest

      - name: Verify container can start
        run: |
          docker run --rm \
            --privileged \
            --cap-add=NET_ADMIN \
            --cap-add=SYS_MODULE \
            -e CI=true \
            ghcr.io/${{ github.repository }}:${{ env.DISTRO }}-${{ matrix.arch }}
          echo "::notice::Container started for ${{ matrix.arch }} on ${{ env.DISTRO }}"

      - name: Success notice
        run: echo "::notice::Image pushed and verified!"
