name: Build, Test & Publish Docker image

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-test-push:
    runs-on: self-hosted
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]

    env:
      # Ваш «дистрибутив+версия», который будет в тегах
      DISTRO: ubuntu22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU (для эмуляции)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.dockerfile
          push: true

          # собираем только для одной платформы за раз
          platforms: linux/${{ matrix.arch }}

          # теги: distro-arch, distro и latest
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.DISTRO }}-${{ matrix.arch }}
            ghcr.io/${{ github.repository }}:${{ env.DISTRO }}
            ghcr.io/${{ github.repository }}:latest

      - name: Verify container can start (CI mode)
        run: |
          docker run --rm \
            --privileged \
            --cap-add=NET_ADMIN \
            --cap-add=SYS_MODULE \
            -e CI=true \
            ghcr.io/${{ github.repository }}:${{ env.DISTRO }}-${{ matrix.arch }}
          echo "::notice::Container started successfully on ${{ matrix.arch }}"

      - name: Success notice
        run: echo "::notice::Image pushed and verified!"
